version: '3'

services:
  node-app-sample:
    build: .
    image: node-app-sample
    environment:
      - MONGODB_URL=mongodb://mongodb-sample:27017/node-boilerplate
    ports:
      - '3000:3000'
    depends_on:
      - mongodb-sample
    volumes:
      - .:/usr/src/node-app
    networks:
      - node-network

  mongodb-sample:
    image: mongo:4.2.1-bionic
    ports:
      - '27017:27017'
    volumes:
      - dbdata:/data/db
    networks:
      - node-network

volumes:
  dbdata:

networks:
  node-network:
    driver: bridge
